CREATE TABLE IF NOT EXISTS users(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    user_name varchar(255) NOT NULL DEFAULT NULL,
    full_name varchar(255) NOT NULL DEFAULT NULL,
    password varchar(255) NOT NULL DEFAULT NULL,
    account_non_expired bit(1) DEFAULT NULL,
    account_non_locked bit(1) DEFAULT NULL,
    credentials_non_expired bit(1) DEFAULT NULL,
    enabled bit(1) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_name)
)